# Containerfile.hlx-grafana-auth-proxy
FROM python:3.12-slim

# Python defaults
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Log level
ENV LOG_LEVEL=INFO

# Create non-root user
# -r = system account, no home
RUN useradd -r -u 1000 appuser

WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install Python-dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app.py .

# set permissions to folder/files
RUN chown -R appuser:appuser /app

# Switch to non root user
USER appuser

ENV GRAFANA_INTERNAL_URL=http://127.0.0.1:3000

EXPOSE 8080

CMD ["uvicorn", "app:app", \
     "--host", "0.0.0.0", \
     "--port", "8080", \
     "--workers", "2", \
     "--proxy-headers", \
     "--log-level", "debug", \
     "--access-log"]



