#############################################
# ConfigMap: Provisionerar Grafana-datakälla
# Använder JSON API-pluginet mot vår proxy
#############################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: helix-grafana-datasources
data:
  helix-datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: Helix REST (JSON API)
        type: marcusolsson-json-datasource
        access: proxy
        # Viktigt:
        #  - Grafana backend (dataproxy) anropar denna URL
        #  - URL pekar på vår FastAPI-proxy i samma pod
        url: http://127.0.0.1:8080/helix-api
        isDefault: false
        jsonData: {}
---
#############################################
# ConfigMap: Helix + Auth-konfiguration
#
# Här lägger du allt som styr:
#  - vilken Helix-bas-URL som används
#  - vilka formulär som är tillåtna
#  - hur grupper mappas till Grafana-roller
#  - hur User-formuläret och fält heter
#  - om du kör AUTH_MODE=local eller AUTH_MODE=rsso
#############################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: helix-grafana-auth-config
data:
  ###########################################
  # Helix REST-bas + JWT-login
  ###########################################
  LOG_LEVEL: "INFO"

  ###########################################
  # Helix REST-bas + JWT-login
  ###########################################
  HELIX_BASE_URL: "http://arserver:8008"
  HELIX_JWT_LOGIN_URL: "http://arserver:8008/api/jwt/login"

  ###########################################
  # Whitelist av Helix-formulär som får nås
  # från Grafana via /helix-api/<form>.
  #
  # Här kan du lägga till t.ex. HPD:IncidentInterface
  # HELIX_ALLOWED_FORMS: "User,Group,HPD:IncidentInterface"
  ###########################################
  HELIX_ALLOWED_FORMS: "User,Group"

  ###########################################
  # Grupp → Grafana-roll-mappning
  #
  # Format: "groupId:Role,groupId:Role,..."
  # Roller måste vara exakt: Viewer, Editor, Admin
  #
  # Exempel:
  #  400001 (Helix-grupp) → Viewer
  #  400002 → Editor
  #  400003 → Admin
  ###########################################
  HELIX_GROUP_ROLE_MAPPING: "400001:Viewer,400002:Editor,400003:Admin"

  ###########################################
  # Formulär + fält för att läsa användarens grupp-lista
  #
  # HELIX_USER_FORM:
  #   Formuläret där användarens grupper ligger (oftast "User")
  #
  # HELIX_USER_LOGIN_FIELD:
  #   Fältet som innehåller login-namnet (t.ex. "Login Name")
  #
  # HELIX_USER_GROUP_FIELD:
  #   Fältet som innehåller grupp-listan (t.ex. "Group List")
  #   Värdet ser ut ungefär: "1;400003;12321;"
  ###########################################
  HELIX_USER_FORM: "User"
  HELIX_USER_LOGIN_FIELD: "Login Name"
  HELIX_USER_GROUP_FIELD: "Group List"

  ###########################################
  # Defaultroll om ingen matchande grupp hittas
  # eller om Helix-queryn misslyckas.
  ###########################################
  HELIX_DEFAULT_GRAFANA_ROLE: "Viewer"

  ###########################################
  # Autentiseringsläge för proxy:
  #
  #  - local (default): egen login-sida mot Helix JWT-login
  #  - rsso: användare autentiseras via RSSO framför,
  #          denna app läser användarnamn från RSSO_HEADER_NAME
  #
  # För RSSO-läge:
  #   AUTH_MODE: "rsso"
  #   RSSO_HEADER_NAME: "X-RSSO-USER"  (eller vad din proxy sätter)
  ###########################################
  AUTH_MODE: "local"
  RSSO_HEADER_NAME: "X-RSSO-USER"
---
#############################################
# Secret: Helix servicekonto (admin user)
#
# Här lägger du det "känsliga":
#  - HELIX_ADMIN_USER
#  - HELIX_ADMIN_PASSWORD
#
# I labb kan du använda stringData så här.
# I produktion kan du skapa / uppdatera Secret separat
# med podman/kubectl.
#############################################
apiVersion: v1
kind: Secret
metadata:
  name: helix-admin-credentials
type: Opaque
stringData:
  HELIX_ADMIN_USER: "Demo"
  HELIX_ADMIN_PASSWORD: "P@ssw0rd"
---
#############################################
# PersistentVolumeClaim: Grafana Storage
#############################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#############################################
# Pod: Grafana + hlx-grafana-auth-proxy
#############################################
apiVersion: v1
kind: Pod
metadata:
  name: helix-grafana-pod
  annotations:
    podman.io/network: helix   # Anslut till befintligt "helix"-nät i podman
spec:
  containers:
    #########################################
    # GRAFANA-CONTAINER
    #########################################
    - name: grafana
      image: docker.io/grafana/grafana:latest
      env:
        # Installera JSON API-datasource plugin
        - name: GF_INSTALL_PLUGINS
          value: "marcusolsson-json-datasource"

        # Grundläggande serverinställningar
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:%(http_port)s/"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "false"

        ##################################################
        # Auth proxy-mode:
        #  - vår hlx-grafana-auth-proxy skickar X-WEBAUTH-USER
        #    och X-WEBAUTH-ROLE till Grafana
        #  - Grafana använder detta som användarnamn + roll
        ##################################################
        - name: GF_AUTH_PROXY_ENABLED
          value: "true"
        - name: GF_AUTH_PROXY_HEADER_NAME
          value: "X-WEBAUTH-USER"
        - name: GF_AUTH_PROXY_HEADER_PROPERTY
          value: "username"
        - name: GF_AUTH_PROXY_AUTO_SIGN_UP
          value: "true"

        # Koppla in roll-headern:
        # Detta betyder: "Role"-attributet ska hämtas från HTTP-headern X-WEBAUTH-ROLE
        - name: GF_AUTH_PROXY_HEADERS
          value: "Role:X-WEBAUTH-ROLE"

        # Viktigt: skicka även grafana-username tillbaka till datakällan
        # i headern X-Grafana-User (används av vår FastAPI för impersonation)
        - name: GF_DATAPROXY_SEND_USER_HEADER
          value: "true"

        # Default-rollen för nya användare om ingen roll sätts från headern
        # (vår proxy försöker dock alltid skicka X-WEBAUTH-ROLE)
        - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
          value: "Viewer"

        # (valfritt: admin-konto för fallback)
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "changeme"

      ports:
        - containerPort: 3000
          protocol: TCP

      volumeMounts:
        # Mounta ConfigMap som provisioning-fil för datasourcen
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        # Persistent lagring för dashboards, users, etc
        - name: grafana-storage
          mountPath: /var/lib/grafana

    #########################################
    # HLX-GRAFANA-AUTH-PROXY (FastAPI)
    #########################################
    - name: hlx-grafana-auth-proxy
      image: localhost/hlx-grafana-auth-proxy:latest
      env:
        # Intern URL där Grafana nås från proxyn
        - name: GRAFANA_INTERNAL_URL
          value: "http://127.0.0.1:3000"

      # Hämta alla övriga auth-/Helix-inställningar från ConfigMap
      envFrom:
        - configMapRef:
            name: helix-grafana-auth-config
        # ...och hämta känsliga värden från Secret
        - secretRef:
            name: helix-admin-credentials

      ports:
        - containerPort: 8080
          hostPort: 8081   # Exponera proxyn på host:8081
          protocol: TCP

  volumes:
    - name: grafana-datasources
      configMap:
        name: helix-grafana-datasources
    - name: grafana-storage
      persistentVolumeClaim:
        claimName: grafana-disk-pvc
