#############################################
# ConfigMap: Provision Grafana data source
# Uses JSON API plugin against our auth proxy
#############################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: helix-grafana-datasources
data:
  helix-datasource.yaml: |
    apiVersion: 1

    datasources:
      - name: Helix REST (JSON API)
        type: marcusolsson-json-datasource
        access: proxy
        # Important:
        #  - Grafana backend (data proxy) will call this URL
        #  - The URL points to our FastAPI proxy inside the same pod
        url: http://127.0.0.1:8080/helix-api
        isDefault: false
        jsonData: {}


---
#############################################
# ConfigMap: Helix + Auth configuration
#
# Here you configure:
#  - Helix base URL
#  - Which forms are allowed
#  - How groups map to Grafana roles
#  - Which Helix form/fields are used for groups
#  - Whether we use AUTH_MODE=local or AUTH_MODE=rsso
#############################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: helix-grafana-auth-config
data:
  ###########################################
  # Log level for the hlx-grafana-auth-proxy
  # Allowed values: DEBUG, INFO, WARNING, ERROR, CRITICAL
  ###########################################
  LOG_LEVEL: "DEBUG"

  ###########################################
  # Helix REST base URL + JWT login endpoint
  ###########################################
  HELIX_BASE_URL: "http://arserver:8008"
  HELIX_JWT_LOGIN_URL: "http://arserver:8008/api/jwt/login"

  ###########################################
  # Whitelist of Helix forms that can be queried
  # from Grafana via /helix-api/<form>.
  #
  # Example to allow incidents:
  # HELIX_ALLOWED_FORMS: "User,Group,HPD:IncidentInterface"
  ###########################################
  HELIX_ALLOWED_FORMS: "User,Group"

  ###########################################
  # Helix group → Grafana role mapping
  #
  # Format: "groupId:Role,groupId:Role,..."
  # Roles must be exactly: Viewer, Editor, Admin
  #
  # Example:
  #  400001 (Helix group) → Viewer
  #  400002 → Editor
  #  400003 → Admin
  ###########################################
  HELIX_GROUP_ROLE_MAPPING: "400001:Viewer,400002:Editor,400003:Admin"


  ###########################################
  # Form + fields used to read the user's group list
  #
  # HELIX_USER_FORM:
  #   Form that contains the user's groups (usually "User")
  #
  # HELIX_USER_LOGIN_FIELD:
  #   Field that contains the Helix login name (e.g. "Login Name")
  #
  # HELIX_USER_GROUP_FIELD:
  #   Field that contains the group list string (e.g. "Group List")
  #   Example value: "1;400003;12321;"
  ###########################################
  HELIX_USER_FORM: "User"
  HELIX_USER_LOGIN_FIELD: "Login Name"
  HELIX_USER_GROUP_FIELD: "Group List"

  ###########################################
  # Default Grafana role if:
  #  - no matching group is found, or
  #  - Helix query fails.
  ###########################################
  HELIX_DEFAULT_GRAFANA_ROLE: "Viewer"

  ###########################################
  # Authentication mode for the proxy:
  #
  #  - local (default): own login page against Helix JWT login
  #  - rsso:  header-based auth, username from RSSO_HEADER_NAME
  #  - oidc:  this service is an OIDC client towards RSSO/HSSO
  #
  # For RSSO header mode:
  #   AUTH_MODE: "rsso"
  #   RSSO_HEADER_NAME: "X-RSSO-USER"
  #
  # For OIDC mode:
  #   AUTH_MODE: "oidc"
  #   OIDC_* variables below must be configured
  ###########################################
  AUTH_MODE: "local"
  RSSO_HEADER_NAME: "X-RSSO-USER"

 ###########################################
  # OIDC configuration (used when AUTH_MODE="oidc")
  #
  # RSSO/HSSO is the OpenID Provider (OP).
  # This container is the OIDC client (RP).
  #
  # NOTE: OIDC_CLIENT_ID and OIDC_CLIENT_SECRET are stored
  #       in a Secret (see helix-oidc-credentials).
  ###########################################
  OIDC_ISSUER: "http://ars.sandbox:8082/realms/ars"
  # EXTERNAL
  OIDC_AUTH_URL: "http://ars.sandbox:8082/rsso/oauth2/authorize"
  # INTERNAL (Container -> Container)
  OIDC_TOKEN_URL: "http://rsso-int:8080/rsso/oauth2/token"
  OIDC_USERINFO_URL: "http://rsso-int:8080/rsso/oauth2/userinfo"

  # EXTERNAL
  # Must match what you configure in RSSO/HSSO client + DNS/front-end:
  OIDC_REDIRECT_URI: "http://ars.sandbox:8081/oidc/callback"

  # Optional tuning:
  OIDC_SCOPE: "openid profile email"
  OIDC_USERNAME_CLAIM: "preferred_username"

  # Secure Cookie Setting, default = "true", use false when testing with sandbox without https
  SECURE_COOKIES: "true"
---
#############################################
# Secret: Helix service account (admin user)
#
# Here you store sensitive data:
#  - HELIX_ADMIN_USER
#  - HELIX_ADMIN_PASSWORD
#
# In a lab environment you can use stringData like this.
# In production you would typically create/update this Secret
# separately with kubectl/podman.
#############################################
apiVersion: v1
kind: Secret
metadata:
  name: helix-admin-credentials
type: Opaque
stringData:
  HELIX_ADMIN_USER: "Demo"
  HELIX_ADMIN_PASSWORD: "P@ssw0rd"
  WEBHOOK_SHARED_SECRET: "super-hemligt-värde-här"
  # Lägg till dessa två – de MÅSTE matcha Grafana-containerns GF_SECURITY_ADMIN_*
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "changeme"
---
#############################################
# OIDC Credentials
#############################################
apiVersion: v1
kind: Secret
metadata:
  name: helix-oidc-credentials
type: Opaque
stringData:
  OIDC_CLIENT_ID: "grafana-helix-proxy"
  OIDC_CLIENT_SECRET: "super-hemligt-oidc-lösen"
---
#############################################
# PersistentVolumeClaim: Grafana Storage
#############################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#############################################
# Pod: Grafana + hlx-grafana-auth-proxy
#############################################
apiVersion: v1
kind: Pod
metadata:
  name: helix-grafana-pod
  annotations:
    podman.io/network: helix   # Attach to existing "helix" network in podman
spec:
  containers:
    #########################################
    # GRAFANA CONTAINER
    #########################################
    - name: grafana
      image: docker.io/grafana/grafana:latest
      env:
        # Install JSON API data source plugin
        - name: GF_INSTALL_PLUGINS
        #  value: "marcusolsson-json-datasource"
          value: "marcusolsson-json-datasource,grafana-clock-panel"

        # Basic server settings
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:%(http_port)s/"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "false"

        # Disable Grafana Live (real-time WebSocket streaming)
        - name: GF_LIVE_ENABLED
          value: "false"

        ##################################################
        # Auth proxy mode:
        #  - hlx-grafana-auth-proxy sends X-WEBAUTH-USER
        #    and X-WEBAUTH-ROLE to Grafana
        #  - Grafana uses this as username + role
        ##################################################
        - name: GF_AUTH_PROXY_ENABLED
          value: "true"
        - name: GF_AUTH_PROXY_HEADER_NAME
          value: "X-WEBAUTH-USER"
        - name: GF_AUTH_PROXY_HEADER_PROPERTY
          value: "username"
        - name: GF_AUTH_PROXY_AUTO_SIGN_UP
          value: "false"

        # Map Role attribute from HTTP header X-WEBAUTH-ROLE
        - name: GF_AUTH_PROXY_HEADERS
          value: "Role:X-WEBAUTH-ROLE,Groups:X-WEBAUTH-GROUPS"

        # Important: also send Grafana username back to the data source
        # in header X-Grafana-User (used by the FastAPI proxy for impersonation)
        - name: GF_DATAPROXY_SEND_USER_HEADER
          value: "true"
        - name: GF_DATAPROXY_USER_HEADER_NAME
          value: "X-Grafana-User"

        # Default org role for new users if no role is set from header
        # (our proxy tries to always send X-WEBAUTH-ROLE)
        - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
          value: "Viewer"

        # Optional: admin account inside Grafana
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "changeme"

      ports:
        - containerPort: 3000
          protocol: TCP

      volumeMounts:
        # Mount ConfigMap as provisioning file for the data source
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        # Persistent storage for dashboards, users, etc
        - name: grafana-storage
          mountPath: /var/lib/grafana

    #########################################
    # HLX-GRAFANA-AUTH-PROXY (FastAPI)
    #########################################
    - name: hlx-grafana-auth-proxy
      image: localhost/hlx-grafana-auth-proxy:latest
      env:
        # Internal URL where Grafana is reachable from the proxy
        - name: GRAFANA_INTERNAL_URL
          value: "http://127.0.0.1:3000"

      # Load all Helix/auth settings from ConfigMap...
      envFrom:
        - configMapRef:
            name: helix-grafana-auth-config
        # ...and load sensitive values from Secret
        - secretRef:
            name: helix-admin-credentials
        - secretRef:
            name: helix-oidc-credentials

      ports:
        - containerPort: 8080
          hostPort: 8081   # Expose the proxy on host:8081
          protocol: TCP

  volumes:
    - name: grafana-datasources
      configMap:
        name: helix-grafana-datasources
    - name: grafana-storage
      persistentVolumeClaim:
        claimName: grafana-disk-pvc
